const ACCESS_TOKEN = 'ABSDCSJFDASD32HDAKJFJADKJFKAJSKDAABCHKDHFDHFD78738237JDKLSDJSKLDJSKLDJ'

const ACCESS_TOKEN_REFRESH = 'SJFDASKAJSKJKDAABCHKDHFDHFD32HDAD78738KGHGJHG237JDKLSDJSKJHKJHKLDJSKLDJ'

const ACCESS_TOKEN_MAILER = 'DHSDSAHGKSJFDASKDHFD32HDAD7AJSKJKDAABCHKDHJSKLDJSKLDJF8738HHK237JDKHGKHLSD'


const TOKEN_TIME_LIFE = '1h'

const TOKEN_TIME_LIFE_REFRESH = '365d'

const TOKEN_TIME_LIFE_MAILER = '1h'


module.exports = {
    ACCESS_TOKEN: ACCESS_TOKEN,
    ACCESS_TOKEN_REFRESH: ACCESS_TOKEN_REFRESH,
    ACCESS_TOKEN_MAILER: ACCESS_TOKEN_MAILER,
    TOKEN_TIME_LIFE: TOKEN_TIME_LIFE,
    TOKEN_TIME_LIFE_REFRESH: TOKEN_TIME_LIFE_REFRESH,
    TOKEN_TIME_LIFE_MAILER: TOKEN_TIME_LIFE_MAILER
}