const INTERVAL_DURATION = 3000;
const SPECIAL_CHARACTERS_REGEX = /[!@#$%^&*(),.?":{}|<>]/;
const UPPERCASE_LETTER_REGEX = /[A-Z]/;
const PHONE_REGEX = /^[0-9]{10}$/;
const TOTAL_ITEM_PRODUCT = 8;
export {
  PHONE_REGEX,
  INTERVAL_DURATION,
  SPECIAL_CHARACTERS_REGEX,
  UPPERCASE_LETTER_REGEX,
  TOTAL_ITEM_PRODUCT,
};
