export const texts = {
  account: {
    INFO: "Tài khoản của tôi",
    PROFILE: "Hồ sơ",
    ADDRESS: "Địa chỉ",
    REPASS: "Đổi mật khẩu",
    ORDER: "Đơn hàng của tôi",
    NOTIFY: "Thông báo của tôi",
    INFO_MANAGER: "Quản lý hồ sơ",
    NAME_LOGIN: "Tên đăng nhập",
    FULL_NAME: "Họ và tên",
    BIRTHDAY: "Ngày sinh",
    SEX: "Giới tính",
    EMAIL: "Email",
    PHONE_NUMBER: "Số điện thoại",
  },
  common: {
    ALL: "all",
    SORT: "Sắp xếp",
    DECREASING: "Giá giảm dần",
    ASCENDING: "Giá tăng dần",
    INFORMATION: "Thông tin",
    EDIT: "Sửa",
    DELETE: "Xóa",
    ADD: "Thêm",
    SAVE: "Lưu",
    EXIT: "Thoát",
    NEW: "New",
    DISCOUNT: "Giảm giá",
    TOTAL_AMOUNT: "Tổng tiền",
    PROVISIONAL: "Tạm tính",
    ADD_TO_CART: "Thêm giỏ hàng",
  },
  header: {
    HOME: "Trang chủ",
    PRODUCT: "Sản phẩm",
    LOGIN: "Đăng nhập",
    REGISTER: "Đăng ký",
    ACCOUNT: "Tài khoản",
    LOGOUT: "Đăng xuất",
  },
  product: {
    HOT: "Hot",
    ALL: "Tất cả",
    PRODUCT_NOT_FOUND: "Thông tin sản phẩm không tồn tại!",
    PRODUCT_LIST: "Danh sách sản phẩm",
    NO_PRODUCT: "Không có sản phẩm nào!",
    SOLD_OUT: "Hết hàng",
    PRODUCT_OTHER: "Sản phẩm khác",
    PRODUCT_NEW: "Sản phẩm mới",
    BEST_SELLER: "Sản phẩm bán chạy nhất",
    AUTHENTIC: "Chính hãng",
  },
  order: {
    NO_ADDRESS: "Bạn chưa có địa chỉ giao hàng!",
    ACCEPT_ORDER: "Xác nhận và đặt hàng",
    SET_ADDRESS: "Thiết lập địa chỉ",
    ADD_ADRESS: "Thêm địa chỉ mới",
    ADDRESS_SHIP: "Địa chỉ giao hàng",
    TOTAL_PAYMENT: "Tổng tiền thanh toán",
    ORDER_NOW: "Đặt hàng ngay",
    FREE_SHIP: "Miễn phí ship",
    FLAS_SHIP: "Giao hàng nhanh",
  },

  search: {
    RESULTS: "Kết quả tìm kiếm",
    NO_RESULTS: "Không tìm thấy sản phẩm nào",
  },
};
